### PR TITLE
Add some features

### LINKED ISSUE #8: eps(BFloat16) not implemented
```julia
julia> using BFloat16s

julia> eps(BFloat16)
ERROR: MethodError: no method matching eps(::Type{BFloat16})
Closest candidates are:
  eps(::Dates.Time) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Dates/src/types.jl:334
  eps(::Dates.Date) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Dates/src/types.jl:333
  eps(::Dates.DateTime) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Dates/src/types.jl:332
  ...
Stacktrace:
 [1] top-level scope at none:0
```
I tried implementing a naive `eps()` using the usual divide by 2 until `1 + ϵ > 1` fails, but then I hit #6.

### LINKED ISSUE #14: round(::BFloat16) not implemented
Probably just adding something like
```julia
Base.round(x::BFloat16, r::RoundingMode{:Up}) = BFloat16(ceil(Float32(x)))
Base.round(x::BFloat16, r::RoundingMode{:Down}) = BFloat16(floor(Float32(x)))
Base.round(x::BFloat16, r::RoundingMode{:Nearest}) = BFloat16(round(Float32(x)))
```
would already do the job?

### LINKED ISSUE #15: Conversion to Int
Probably just adding
```julia
Base.Int64(x::BFloat16) = Int64(Float32(x))
Base.Int32(x::BFloat16) = Int32(Float32(x))
```

### PR DESCRIPTION
**Pull request by amontoison**
close #8
close #14
close #15

### CODE REVIEW

**Comment by amontoison** [comment]
@Keno

**Comment by amontoison** [comment]
@milankl

**Comment by amontoison** [comment]
bump

**Comment by dpo** [comment]
Thanks!

**Pull request merged**
