### PR TITLE
Additional conversions, one&zero, bitstring, round, next/prevfloat, etc + tests

### PR DESCRIPTION
**Pull request by milankl**

### CODE REVIEW

**Comment by milankl** [comment]
I've decided to move the stochastic rounding to a separate package called [StochasticRounding.jl](https://github.com/milankl/StochasticRounding.jl). The PR now only contains some new features for BFloat16 such as

- conversion to and from Float16, Int
- power, trigonometric functions via conversion
- round, floor, ceil
- nextfloat, prevfloat
- bitstring
- Travis with Julia 1.3
- version to 0.2

**Comment by dpo** [comment]
@milankl This repository was recently moved to JuliaMath. Could I ask you to rebase this pull request? Thanks!

**Comment by milankl** [comment]
Will do in the next days, thanks. I'll probably just pull request a branch without all those commits that were undone by other commits. Sorry for the mess.

**Comment by dpo** [comment]
Many thanks!

**Pull request closed without merging**
