### PR TITLE
Base.decompose(::BFloat16)

### PR DESCRIPTION
**Pull request by milankl**
Following ideas of

https://github.com/JuliaLang/julia/blob/cdec4c21bdfffa9b198b8ecdde83aa082ebfc4e9/base/float.jl#L736-L756

So that

```
s,e,d = Base.decompose(x::BFloat16)
BFloat16(s*2^e/d) == x
```

### CODE REVIEW

**Comment by ViralBShah** [comment]
@oscardssmith merge?

**Comment by oscardssmith** [comment]
I thought our `BFloat16` plan was to not do anything other than the LLVM intrinsics in Base, and let a package add all the methods, but I might be mistaken here.

**Comment by ViralBShah** [comment]
@milankl Let me know if you'd find it useful to have commit access to this package.

**Review by oscardssmith — APPROVED** [review]

**Comment by milankl** [comment]
> I thought our `BFloat16` plan was to not do anything other than the LLVM intrinsics in Base, and let a package add all the methods, but I might be mistaken here.

Shouldn't the _long-term_ plan be to have `BFloat16` in Base as are Float16/32/64? But to be less intrusive for now and not do all the work at once, have this package where we/users of `BFloat16` can add all missing methods they need for BFloat16? Hopefully we will then eventually reach a maturity here that we can think about moving some of the `BFloat16` support into Base? I feel it just requires more general hardware support for people to actively use BFloat16s.jl till then we can happily add methods here?

**Comment by milankl** [comment]
> @milankl Let me know if you'd find it useful to have commit access to this package.

Yes, I'd be happy to add more methods here whenever I work with BFloat16!

**Pull request merged**
