### PR TITLE
Add bitstring, nextfloat, prevfloat, performance measures and tests

### PR DESCRIPTION
**Pull request by milankl**

### CODE REVIEW

**Comment by milankl** [comment]
I'll add some more tests soon so that this can be merged.

**Comment by staticfloat** [comment]
I know this PR has languished for a while; if you're still interested, can you rebase?

**Comment by milankl** [comment]
Thanks, too busy now, but will rebase soon!

**Comment by bjarthur** [comment]
would be nice to have the `{next,prev}float` herein!

**Comment by milankl** [comment]
I'll close this one, but prev/nextfloat is now a PR in #38

**Pull request closed without merging**
